### ISSUE TITLE
Doesn't handle standard .git bare repo suffix

### ISSUE THREAD

**Issue by mpnordland** [prashanthellina/pullbox#2]
I have a git repo that I set up to handle syncing school work between my computers. I'd like to start using pullbox to handle syncing them automatically. How do I get it to work with an existing repo?

**Comment by mpnordland** [comment]
So I figured out that it was failing because my repo followed the standard for naming bare repos: `<reponame>.git`. All of the git tools understand this convention and handle it properly. I'm working up a pull request that will make pullbox do this too.

**Comment by prashanthellina** [comment]
@mpnordland Could you try specifying the `path` command line argument with the ".git" suffix?

**Comment by mpnordland** [comment]
I did, however because git knows to remove that suffix, it can't find the cloned repo. `repo.git` becomes just `repo`.

**Comment by prashanthellina** [comment]
Ah I see. I did not try this for my use-case. I look forward to your code
changes.

Also, when I wrote this tool, I wasn't aware of `syncthing`(
https://syncthing.net/). I've replaced `pullbox` with `syncthing` and like
it so far. You might want to give it a try.

**Comment by mpnordland** [comment]
Well, turns out my school's network won't let me use syncthing, so pullbox is the way to go for me.
